### ISSUE TITLE
Inkonsistente Verwendung von super()

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/group11-exercise1#15]
Die Angabe von `super()` im Konstruktor der Kindklasse ist optional, da der `super()`-Aufruf vom Compiler automatisch generiert wird.

Im Konstruktor `Vector()` wird kein `super()` angegeben, im Konstruktor `Vector(double x, double y, double z)` wird es aber benutzt.

Entweder sollte man es immer oder nie angeben.

**Comment by maxGross** [comment]
erledigt
