### ISSUE TITLE
Instanzvariablen in einem Statement deklariert

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/group11-exercise1#17]
Anstatt alle drei Instanzvariablen (`x`, `y`, `z`) in einem Statement zu deklarieren, sollte man drei einzelne Deklarationen angeben. Hierdurch hat man die Möglichkeit, die Variablen einzeln zu kommentieren und der Code wird übersichtlicher.

**Comment by maxGross** [comment]
erledigt
