### ISSUE TITLE
Methoden: multipliziere

### ISSUE THREAD

**Issue by Rahtainka** [tpe-lecture/group11-exercise1#2]
Multiplikation des Vektors mit einem Skalar.
Multiplikation des Vektors mit einem Vektor.

**Comment by maxGross** [comment]
Laut Junit stimmt der Code nicht. In Testprojekt mit gleichem Code bringt er richtiges Ergebnis .. Idee?

**Comment by maxGross** [comment]
Mult Skalar überarbeitet, Junit Test weiterhin fehlerhaft 8db3638c8ff1e3199378eed5514de4ff6b3f411d

**Comment by wagnst** [comment]
![multiplicate](https://cloud.githubusercontent.com/assets/7312523/6656319/043c59c0-cb26-11e4-9cf1-c289e328bead.JPG)
also bei mir steht da einfach ein falsches Ergebnis :D

**Comment by wagnst** [comment]
please use double... then it works :-)
implemented in e64583d20da9bf4d680888fba86a6cb1165b6688
