### ISSUE TITLE
Division durch 0 in einheitsvektor

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/group11-exercise1#20]
Eine mögliche Division durch 0 in der Methode `einheitsvektor()` wird nicht abgefangen. Die deklarierte Ausnahme ist nur Dekoration.

**Comment by maxGross** [comment]
4c364026daa3383f498ee187fc22d592eda75db4
Code entsprechend angepasst um Division durch 0 zu verhindern

**Comment by wagnst** [comment]
Bitte noch JavaDoc aktualisieren / exception schmeissen?..

https://github.com/tpe-lecture/group11-exercise1/commit/4c364026daa3383f498ee187fc22d592eda75db4#diff-9ef7893c9ee0a57df0e65a053bc26d6aR117

**Comment by maxGross** [comment]
https://github.com/tpe-lecture/group11-exercise1/blob/master/Kyrat/src/Vector.java#L111

wurde bereits berichtigt ..
