### ISSUE TITLE
Hash-Code streut nicht gut

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/group11-exercise1#23]
Durch die Art, wie der Hash-Code berechnet wird, streuen die generierten Hash-Codes schlecht. Besser wäre folgende Implementierung:

```java
/**
  * @see java.lang.Object#hashCode()
  */
@Override
public int hashCode() {
    return Arrays.hashCode(new double[] { x, y, z } );
}
```

**Comment by maxGross** [comment]
Implementierung angepasst - zusätzlich notwendiges package java.util.Arrays importiert
