### ISSUE TITLE
Methode: kreuzprodukt

### ISSUE THREAD

**Issue by Rahtainka** [tpe-lecture/group11-exercise1#6]
Bestimmt das Kreuzprodukt dises mit dem gegebenen Vektor.

**Comment by maxGross** [comment]
JUnit Test sagt nein! Nachprüfung über Testprogramm sagt ja :D f8f8f8fece740d4cec1aa375433f5384c0514a81

**Comment by wagnst** [comment]
implemented and fixed in 5355ff0c42bb400026c5f63e562e37cf7934c1eb
please use double...
